import { StyleSheet, Dimensions } from 'react-native';

const { height } = Dimensions.get('window');

export default StyleSheet.create({
    logoTextStyle: {
        fontSize: 28,
        color: '#FFF',
        fontFamily: 'Ubuntu-Medium',
    },
    smallBlueTextStyle: {
        fontSize: 12,
        color: '#2A4065',
        fontFamily: 'Ubuntu-Regular',
    },
    xLargeTextStyle: {
        fontSize: 48,
        color: '#DDD',
        fontFamily: 'Ubuntu-Bold',
    },
    largeTextStyle: {
        fontSize: 28,
        color: '#DDD',
        fontFamily: 'Ubuntu-Regular',
    },
    mediumTextStyle: {
        fontSize: 20,
        color: '#DDD',
        fontFamily: 'Ubuntu-Regular',
    },
    smallTextStyle: {
        fontSize: 12,
        color: '#DDD',
        fontFamily: 'Ubuntu-Light',
    },
    inputStyle: {
        flex: 5,
        fontSize: 14,
        paddingLeft: 20,
        paddingRight: 20,
        color: '#2D2D2D',
        fontFamily: 'Ubuntu-Regular',
    },
    containerStyle: {
        padding: 10,
        paddingLeft: 20,
        paddingRight: 20,
        position: 'relative',
        flexDirection: 'row',
        justifyContent: 'center',
    },
    cardStyle: {
        paddingTop: 10,
        height: '100%',
        alignItems: 'center',
        justifyContent: 'center',
    },
    btnConfirm: {
        flex: 1,
        padding: 5,
        elevation: 4,
        borderWidth: 2,
        borderRadius: 5,
        alignSelf: 'stretch',
        borderColor: '#2A4065',
        backgroundColor: '#2A4065',
    },
    btnCancel: {
        flex: 1,
        elevation: 4,
        borderWidth: 2,
        borderRadius: 5,
        alignSelf: 'stretch',
        borderColor: '#CC2820',
        backgroundColor: '#CC2820',
    },
    btnTextStyle: {
        fontSize: 16,
        color: '#fff',
        paddingTop: 10,
        paddingBottom: 10,
        alignSelf: 'center',
        fontFamily: 'Ubuntu-Medium',
    },
    spinnerStyle: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    scrollViewStyle: {
        height: '100%',
    },
    modalScrollViewStyle: {
        marginTop: 75,
        height: '100%',
        marginBottom: 20,
    },
    mapStyle: {
        height: 300,
        width: '100%'
    },
    mapLocalizacaoStyle: {
        width: '100%',
        height: height - 80,
    },
    eventCardStyle: {
        elevation: 8,
        marginLeft: 10,
        marginRight: 10,
        marginBottom: 10,
        borderRadius: 10,
        backgroundColor: '#ffff',
    },
    searchBarStyle: {
        flex: 1,
        padding: 20,
        width: '100%',
        position: 'absolute'
    },
    iconInsideSearchBarStyle: {
        width: 30,
        height: 30,
        marginRight: 5,
        borderRadius: 50,
        justifyContent: 'center',
    },
    iconButtomStyle: {
        width: 60,
        height: 60,
        margin: 15,
        elevation: 8,
        borderRadius: 150,
        alignContent: 'center',
        justifyContent: 'center'
    },
    iconButtomEventStyle: {
        width: 50,
        height: 50,
        margin: 15,
        elevation: 8,
        borderRadius: 150,
        alignContent: 'center',
        justifyContent: 'center'
    },
    viewListItensFoundStyle: {
        flex: 1,
        zIndex: 1,
        elevation: 8,
        width: '100%',
        marginTop: 65,
        paddingLeft: 18,
        paddingRight: 18,
        position: 'absolute',
    },
    flatListStyle: {
        borderWidth: 2,
        borderColor: '#FFF',
        borderBottomLeftRadius: 6,
        borderBottomRightRadius: 6,
    },
    backgroudTextFlatListStyle: {
        flex: 1,
        borderTopWidth: 2,
        flexDirection: 'row',
        borderTopColor: '#777',
        backgroundColor: 'white'
    },
    textFlatListStyle: {
        flex: 5,
        height: 40,
        padding: 13,
        fontSize: 12,
        color: '#777',
        backgroundColor: 'white',
        fontFamily: 'Ubuntu-Regular',
    },
    buttomCloseStyle: {
        width: 20,
        height: 20,
        marginRight: 10,
        borderRadius: 25,
        alignContent: 'center',
        justifyContent: 'center',
        backgroundColor: '#CC2820',
    },
    cardHelperStyle: {
        flex: 1,
        zIndex: 1,
        padding: 5,
        bottom: 130,
        elevation: 4,
        borderRadius: 5,
        alignSelf: 'center',
        position: 'absolute',
        backgroundColor: '#FFF',
    },
    errorTextStyle: {
        flex: 5,
        fontSize: 14,
        paddingTop: 5,
        marginLeft: 20,
        color: '#CC2820',
        textAlign: 'center',
        fontFamily: 'Ubuntu-Regular',
    },
    dicaTextStyle: {
        flex: 5,
        fontSize: 14,
        paddingTop: 5,
        marginLeft: 20,
        color: '#2BA3DA',
        textAlign: 'center',
        fontFamily: 'Ubuntu-Regular',
    },
    textCardHelperStyle: {
        flex: 4,
        padding: 5,
        fontSize: 12,
        color: '#777',
        textAlign: 'center',
        fontFamily: 'Ubuntu-Regular',
    },
    headerModalStyle: {
        flex: 1,
        paddingBottom: 3,
        borderBottomWidth: 1,
        flexDirection: 'row',
        borderBottomColor: '#777',
    },
    titleModalStyle: {
        flex: 1,
        color: '#777',
        fontSize: 17,
        paddingTop: 5,
        marginLeft: 50,
        fontFamily: 'Ubuntu-Regular',
    },
    textModalStyle: {
        flex: 1,
        fontSize: 12,
        paddingLeft: 5,
        color: '#777',
        alignItems: 'center',
        fontFamily: 'Ubuntu-Regular',
    },
    backgroundModalStyle: {
        flex: 1,
        paddingBottom: 7,
        borderTopWidth: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        borderBottomColor: '#777',
    },
    viewInput: {
        flex: 1,
        padding: 5,
        elevation: 8,
        borderRadius: 5,
        borderColor: '#FFF',
        flexDirection: 'row',
        backgroundColor: '#FFF'
    }
});
